### ISSUE TITLE
No option to infinite pulsing

### ISSUE THREAD

**Issue by rahulr4** [jackpocket/android-pulse-indicator#3]
Hi,
I do not see any option to pulse infinitely.
Is there any support?

**Comment by mattsilber** [comment]
There's no real option for any kind of indefinite pulsing, but you could set the duration (`setDurationMs(long)`) to something absurdly high (e.g. `TimeUnit.DAYS.toMillis(1)`) to let it just keep going. 

You would then need to manually call `stopPulsing()` in order to finish (somewhere like your Activity's `onPause()`). If you want to stop it a little more gracefully, you could call `suspendPulseCreation()` and wait `pulseLifeSpanMs` before calling `stopPulsing()`

**Comment by rahulr4** [comment]
I would hope there is this functionality in the future. An option to run animation indefinitely
